repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.8
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.12.8'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, jupyter]
      - id: ruff-format
        types_or: [python, jupyter]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        entry: python3 -m mypy --config-file health_rec/pyproject.toml
        language: system
        types: [python]
        exclude: 'tests'

  - repo: https://github.com/crate-ci/typos
    rev: v1  # v1.19.0
    hooks:
      - id: typos
        args: []

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: local
    hooks:
      - id: prettier-js-format
        name: prettier-js-format
        entry: npm run format:fix
        files: 'app/'
        language: node
        types: [javascript]
        additional_dependencies:
          - npm
          - prettier

  - repo: local
    hooks:
      - id: nextjs-lint
        name: Next.js Lint
        entry: npm run lint
        language: system
        types: [javascript, jsx, tsx]
        pass_filenames: false

ci:
  autofix_commit_msg: |
    [pre-commit.ci] Add auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [mypy, prettier-js-format, nextjs-lint]
  submodules: false
