services:
  frontend-dev:
    profiles: ["frontend"]
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
        - BACKEND_PORT=${BACKEND_PORT}
        - BACKEND_HOST=${BACKEND_HOST}
    image: vectorinstitute/health-rec:frontend-dev-${BUILD_ID}
    env_file: .env.development
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=${BACKEND_HOST}
      - NEXT_PUBLIC_BACKEND_PORT=${BACKEND_PORT}
      - NEXT_PUBLIC_FRONTEND_PORT=${FRONTEND_PORT}
      - NEXT_PUBLIC_MAPBOX_API_KEY=${MAPBOX_API_KEY}
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - backend-dev
    networks:
      - app-network

  backend-dev:
    build:
      context: ./health_rec
      dockerfile: Dockerfile.dev
      args:
        - BACKEND_PORT=${BACKEND_PORT}
        - FRONTEND_PORT=${FRONTEND_PORT}
    image: vectorinstitute/health-rec:backend-dev-${BUILD_ID}
    env_file: .env.development
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - CHROMA_HOST=${CHROMA_HOST}
      - CHROMA_PORT=${CHROMA_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COLLECTION_NAME=${COLLECTION_NAME}
    volumes:
      - ./health_rec:/app
      - ${DATA_DIR}:/data
    networks:
      - app-network
    depends_on:
      chromadb-dev:
        condition: service_healthy

  chromadb-dev:
    image: ghcr.io/chroma-core/chroma:1.0.20
    volumes:
      - chroma_data_dev:/chroma/chroma
    ports:
      - "${CHROMA_PORT}:8000"
    environment:
      - ALLOW_RESET=true
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8000"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  chroma_data_dev:

networks:
  app-network:
    driver: bridge
