services:
  frontend:
    profiles: ["frontend"]
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
        - BACKEND_PORT=${BACKEND_PORT}
        - BACKEND_HOST=${BACKEND_HOST}
        - NEXT_PUBLIC_MAPBOX_API_KEY=${MAPBOX_API_KEY}
    image: vectorinstitute/health-rec:frontend-${BUILD_ID}
    env_file: .env.production
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      - 3000:3000
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=${BACKEND_HOST}
      - NEXT_PUBLIC_BACKEND_PORT=${BACKEND_PORT}
      - NEXT_PUBLIC_FRONTEND_PORT=${FRONTEND_PORT}
      - NEXT_PUBLIC_MAPBOX_API_KEY=${MAPBOX_API_KEY}
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./health_rec
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=${BACKEND_PORT}
        - FRONTEND_PORT=${FRONTEND_PORT}
    image: vectorinstitute/health-rec:backend-${BUILD_ID}
    env_file: .env.production
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - CHROMA_HOST=${CHROMA_HOST}
      - CHROMA_PORT=${CHROMA_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COLLECTION_NAME=${COLLECTION_NAME}
    networks:
      - app-network
    depends_on:
      chromadb:
        condition: service_healthy

  chromadb:
    image: ghcr.io/chroma-core/chroma:1.0.20
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "${CHROMA_PORT}:8000"
    environment:
      - ALLOW_RESET=true
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8000"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  chroma_data:

networks:
  app-network:
    driver: bridge
