FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir uv

COPY . .

RUN uv sync --dev --group docs --group eval

ARG BACKEND_PORT
ARG FRONTEND_PORT
ENV BACKEND_PORT=${BACKEND_PORT}
ENV FRONTEND_PORT=${FRONTEND_PORT}

# Print port values
RUN echo "FRONTEND_PORT: ${FRONTEND_PORT}"
RUN echo "BACKEND_PORT: ${BACKEND_PORT}"

EXPOSE ${BACKEND_PORT}

# Use shell form to ensure environment variable expansion
CMD sh -c "uv run uvicorn api.main:app --host 0.0.0.0 --reload --port ${BACKEND_PORT}"
