name: docs

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/docs_build.yml
      - .github/workflows/docs_deploy.yml
      - '**.py'
      - '**.ipynb'
      - '**.html'
      - '**.js'
      - poetry.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: 'true'
      - name: Install uv
        uses: astral-sh/setup-uv@4db96194c378173c656ce18a155ffc14a9fc4355
        with:
          # Install a specific version of uv.
          version: "0.5.21"
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with:
          python-version-file: "health_rec/.python-version"

      - name: Install the project
        run: |
          cd health_rec
          uv sync --all-extras --all-groups

      - name: Build docs
        run: |
          source health_rec/.venv/bin/activate
          cd docs && rm -rf source/reference/api/_autosummary && uv run make html

      - name: Deploy to Github pages
        uses: JamesIves/github-pages-deploy-action@15de0f09300eea763baee31dff6c6184995c5f6a
        with:
          branch: github_pages
          folder: docs/build/html
